### ISSUE TITLE
Set up mongodb and mongoose setting for database settings

### ISSUE THREAD

**Issue by ezkemboi** [kemboijs/nodejs-api-cli#2]
When using a database, there are a lot of people that use the mongo database. 
In addition, they also make use of a mongoose  ORM. 
Thus, we need settings for the same in the best way possible.

**Comment by ezkemboi** [comment]
@Nicanor008, any plans here?

**Comment by Nicanor008** [comment]
@ezkemboi has been a long time checking on it, let me check this week and I'll update this

**Comment by ezkemboi** [comment]
Thank you @Nicanor008. 
I have also done a little change in folder/file structure and made updates. 
I will appreciate any support. 
In case of any questions, please do let me know.

**Comment by Nicanor008** [comment]
Hey @ezkemboi , can someone kindly pick this issue. I am not as free as how I had anticipated. When I'll be free, I'll pick any other issues to work on.

**Comment by ezkemboi** [comment]
Alright, @Nicanor008. Thanks for letting us know.

**Comment by its-tayo** [comment]
@ezkemboi can you assign this to me, please?

**Comment by ezkemboi** [comment]
@its-tayo I think #64 handles this case if I am not wrong.

**Comment by ezkemboi** [comment]
@its-tayo have you ever worked with mysql in NodeJS? 
If so or willing to do that, then I will create a ticket for the same.

**Comment by its-tayo** [comment]
@ezkemboi yes #64 already sorts this, you can create a ticket for mysql +  NodeJS. I haven't worked with mysql in NodeJS but I should be able to handle it.

**Comment by ezkemboi** [comment]
#68 @its-tayo
