### ISSUE TITLE
Set up linter for the project using something like prettier

### ISSUE THREAD

**Issue by ezkemboi** [kemboijs/nodejs-api-cli#25]
Under discussion.

**Comment by ezrqnkemboi** [comment]
Also, to help us more, we can look at this document and give more suggestions 
https://eslint.org/docs/rules/

**Comment by ezrqnkemboi** [comment]
We can also work on commit rules and allow some rules to pass before someone can push. 
That is, determine the workflow of the application.

**Comment by its-tayo** [comment]
@ezkemboi for eslint, I think we can use one of the popular configs like Airbnb or Google. For commit rules, we can use commitlint/commitzen for enforcing commit message formats. Apart from commit message formatting, is there any other thing we need to set in commit hooks (like code linting before pushing...)?

**Comment by ezkemboi** [comment]
I think code linting is before the commit hooks. 
Let's make use of `Airbnb`

**Comment by its-tayo** [comment]
Hi @ezkemboi, I just finished setting up eslint and prettier, should I go ahead with fixing all issues as well or leave that to you?

**Comment by its-tayo** [comment]
> Hi @ezkemboi, I just finished setting up eslint and prettier, should I go ahead with fixing all issues as well or leave that to you?

Hi @ezkemboi, waiting for you take on this.

**Comment by ezkemboi** [comment]
@its-tayo go ahead fixing the issues bro. 
I am expecting to review some of the work tonight and tomorrow and merge. 
You can take any issue and raise a PR.

**Comment by ezkemboi** [comment]
@its-tayo take this one.

**Comment by its-tayo** [comment]
@ezkemboi no worries, will do so.
