### ISSUE TITLE
run linter when the app is generated to format the .js files created

### ISSUE THREAD

**Issue by ezkemboi** [kemboijs/nodejs-api-cli#47]
- some of the files created are not well formated when the app is created.
- There is a need to set up basic linter for the app so that it looks structured when someone sets up the app.

**Comment by its-tayo** [comment]
@ezkemboi I'll take a look at this.

**Comment by ezkemboi** [comment]
@its-tayo this one for the app created by the user. 
Also, check #25 to set a linter for this project.

**Comment by its-tayo** [comment]
Alright.

**Comment by ezkemboi** [comment]
@its-tayo I fixed some items here. It is done.
