### ISSUE TITLE
Add helper function to add response

### ISSUE THREAD

**Issue by hezronkimutai** [kemboijs/nodejs-api-cli#66]
In the generated app, we have similar  code blocks which could be instead kept in a function  so as to increase the maintainability of the generated app. an example of such code block is
``` 
res.status(400).send({
     message: "An error occurred while creating user"
});
```

**Comment by ezkemboi** [comment]
@hezronkimutai, were we able to merge this into the master, please do confirm so that we can close the issue.

**Comment by ezkemboi** [comment]
Already solved.
