### ISSUE TITLE
Change welcome to my first app to welcome to nameOfApp

### ISSUE THREAD

**Issue by ezkemboi** [kemboijs/nodejs-api-cli#99]
**Is your feature request related to a problem? Please describe.**

Inside the s`rc/routes/index.js`, the following code is created 

```javascript
router.get('/', (req, res) => {
  res.status(200).send({
    message: 'Welcome to my first app'
  })
})
```
**Describe the solution you'd like**
I would suggest having it created as 
```javascript
router.get('/', (req, res) => {
  res.status(200).send({
    message: 'Welcome to ${nameOfTheApplicationUsedToCreate}'
  })
})
```

Where the `nameOfTheApplicationUsedToCreate` is the name that the user input when doing `nodejs-api-cli init`

**Describe alternatives you've considered**
Any suggestion is welcome

**Additional context**
N/A

**Comment by leonardxfce** [comment]
I can help with this!

**Comment by ezkemboi** [comment]
Sure @leonardxfce.

**Comment by ezkemboi** [comment]
Just raise a PR and I will take a look. If all is well, then I will go ahead, review and merge.

**Comment by leonardxfce** [comment]
Apologies for this but it task is too difficult for me. I'll leave.

**Comment by ezkemboi** [comment]
If you need any help with this, I can offer it. 
There are also other tasks that are easier. 
Just do let me know how I can help

**Comment by README1ST** [comment]
Can I pick this up please?

**Comment by ezkemboi** [comment]
Sure. Thanks for your contribution @README1ST
